name: "TF-Destroy"
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  Plan_Dev_Destroy:
    runs-on: ubuntu-latest
    environment: null #(Optional) If using GitHub Environments          
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Dev TF Plan
        uses: Pwd9000-ML/terraform-azurerm-plan@v1.2.3
        with:
          path: "./Folder"                 
          plan_mode: "deploy"                     
          tf_version: "latest"                     
          tf_vars_file: "config-dev.tfvars"         
          tf_key: "state"                
          enable_TFSEC: false                       
          az_resource_group: "resource-group-name" ## (Required) AZ backend - AZURE Resource Group hosting terraform backend storage account
          az_storage_acc: "storage-account-name"   ## (Required) AZ backend - AZURE terraform backend storage account
          az_container_name: "container-name"      ## (Required) AZ backend - AZURE storage container hosting state files 
          arm_client_id: ${{ secrets.ARM_CLIENT_ID }}              
          arm_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}     
          arm_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }} 
          arm_tenant_id: ${{ secrets.ARM_TENANT_ID }}             
          github_token: ${{ secrets.GITHUB_TOKEN }} 
