name: 'Terraform'

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# env:  
#   ARM_USE_MSI: true

jobs:
  configuration_01:
    name: Configuration 01
    environment: 'Production'
    uses: origin-technologies/Terraform/.github/workflows/managed_identity_workflow.yml@main
    # with:
    #   environment: Production
    secrets:
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}    
      STORAGE_RESOURCE_GROUP: ${{ secrets.STORAGE_RESOURCE_GROUP }}
      STORAGE_ACCOUNT: ${{ secrets.STORAGE_ACCOUNT }}
      STORAGE_CONTAINER_NAME: ${{ secrets.STORAGE_CONTAINER_NAME }}
